WIDTH, HEIGHT = 960, 540
FPS = 60
FONT = "Juice ITC"
#button properties
BTN_RADIUS = 22
BTN_GAP = 20
#color
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)

HANGMAN_STATUS = 0
LEVEL = 1
SUBJECT_INDEX = 0
SUBJECT = ["ANIMALS", "SPORTS", "FOODS", "JOBS"]
WORD_LIST = [[""], ["A", "FOOTBALL", "VOLLEYBALL", "TENNIS"], [], []]
#0: START MENU
#1: CHOOSE SUBJECT
#2: GAME START
#3: GAME END
GAME_STATUS = 2



