WIDTH, HEIGHT = 960, 540
FPS = 60
FONT = "juice itc"
# button properties
BTN_RADIUS = 22
BTN_GAP = 20
# color
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)

HANGMAN_STATUS = 0
LEVEL = 1
SUBJECT_INDEX = 0
SUBJECT = ["ANIMALS", "SPORTS", "JOBS", "FRUIT", "FESTIVAL", "FOOD", "SCHOOL", "SUBJECTS", "HOUSE", "WEATHER"]
WORD_LIST = [["CAT", "CATERPILLAR", "DONKEY", "ELEPHANT", "FROG"],
             ["BADMINTON", "DIVING", "FOOTBALL", "SWIMMING", "TENNIS"],
             ["ARTIST", "ENGINEER", "POET", "POLICE", "PROGRAMMER"],
             ["COCONUT", "GRAPE", "LYCHEE", "MANGOSTEEN", "PINEAPPLE"],
             ["EASTER", "HALLOWEEN", "VALENTINE", "THANKSGIVING", "CHRISTMAS"],
             ["SALAD", "BREAD", "HAMBURGER", "NOODLES", "PIZZA"],
             ["CLASSROOM", "LIBRARY", "LABORATORY", "PLAYGROUND", "SCHOOLYARD"],
             ["HISTORY", "GEOGRAPHY", "CHEMISTRY", "PHYSICS", "SCIENCE"],
             ["BATHROOM", "KITCHEN", "GARAGE", "BEDROOM", "BALCONY"],
             ["SUNNY", "WINDY", "RAINDROP", "FROST", "DRIZZLE"]]

# 0: START MENU
# 1: CHOOSE SUBJECT
# 2: GAME START
# 3: GAME END
# 4: GAME WIN
GAME_STATUS = 0
